resources:
# Virtual Machine in the Netherlands to run our app
- name: index-analyzer-web-1
  type: compute.v1.instance
  properties:
    zone: europe-west4-a
    machineType: zones/europe-west4-a/machineTypes/n1-standard-1
    metadata:
      items:
        - key: startup-script
          value: docker run -e TARGET_COUNTRY=NL -e STREAMLIT_SERVER_PORT=8080 -p 8080:8080 dipanjank/index-analyzer:latest
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/cos-cloud/global/images/family/cos-89-lts
    networkInterfaces:
    - network: global/networks/default
      accessConfigs:
      - name: 'external-nat'
        type: 'ONE_TO_ONE_NAT'
    tags:
      items:
        - index-analyzer-web

# Allow TCP traffic to port 8080 of the compute engine VM from anywhere
- name: index-analyzer-web-ingress
  type: compute.v1.firewall
  properties:
    network: https://www.googleapis.com/compute/v1/projects/myproject/global/networks/default
    targetTags: [ "index-analyzer-web" ]
    sourceRanges: [ "0.0.0.0/0" ]
    allowed:
      - IPProtocol: TCP
        ports: [ "8080" ]
